### ISSUE TITLE
Current tag of turf-tin creates invalid Polygons

### ISSUE THREAD

**Issue by tcql** [Turfjs/turf-tin#7]
Due to [recent changes](https://github.com/Turfjs/turf-polygon/commit/fb33cf2e0bed9a0ffc91bed5cec019f0a61efac6) in turf-polygon, which were just tagged, tin now fails because the tagged version builds triangles like so (no closing point): 

```
var coords = [[[triangle.a.x, triangle.a.y], [triangle.b.x, triangle.b.y], [triangle.c.x, triangle.c.y]]];
var poly = polygon(coords, {a: null, b: null, c: null});
```

The version currently on master works fine in that respect, so we just need to tag a new version, I believe (unless there are other outstanding issues with what's on master)

**Comment by morganherlocker** [comment]
updated here and in turf master
